export const GET_CATEGORIZED_PRODUCTS = 'GET_CATEGORIZED_PRODUCTS'
export const START_PRODUCT_LOADING = 'START_PRODUCT_LOADING'
export const PRODUCT_ERROR = 'PRODUCT_ERROR'

export const GET_CATEGORIES = 'GET_CATEGORIES'
export const START_CATEGORY_LOADING = 'START_CATEGORY_LOADING'
export const CATEGORY_ERROR = 'CATEGORY_ERROR'
export const INITIAL_CATEGORIZED_PRODUCTS = 'INITIAL_CATEGORIZED_PRODUCTS'