export const GET_CATEGORIZED_PRODUCTS_SHOP = 'GET_CATEGORIZED_PRODUCTS_SHOP'
export const START_PRODUCT_LOADING_SHOP = 'START_PRODUCT_LOADING_SHOP'
export const PRODUCT_ERROR_SHOP = 'PRODUCT_ERROR_SHOP'

export const GET_CATEGORIES_SHOP = 'GET_CATEGORIES_SHOP'
export const START_CATEGORY_LOADING_SHOP = 'START_CATEGORY_LOADING_SHOP'
export const CATEGORY_ERROR_SHOP = 'CATEGORY_ERROR_SHOP'
export const INITIAL_CATEGORIZED_PRODUCTS_SHOP = 'INITIAL_CATEGORIZED_PRODUCTS_SHOP'