export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCT = 'GET_PRODUCT'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const START_PRODUCT_LOADING = 'START_PRODUCT_LOADING'
export const PRODUCT_ERROR = 'PRODUCT_ERROR'

export const GET_ORDERS = 'GET_ORDERS'
export const START_ORDER_LOADING = 'START_ORDER_LOADING'
export const ORDER_ERROR = 'ORDER_ERROR'

export const GET_CATEGORIES = 'GET_CATEGORIES'
export const START_CATEGORY_LOADING = 'START_CATEGORY_LOADING'
export const CATEGORY_ERROR = 'CATEGORY_ERROR'